### ISSUE TITLE
Комменты

### ISSUE THREAD

**Issue by dmordvinov** [igor-sumin/CodeNamesDemo#1]
1. Интересно, а почему я не могу получить userData без ссылки на конкретную комнату?
2. Можно удалять null поля из серилизации DTO объхектов (например roomDTO - teams) указав @JsonInclude(JsonInclude.Include.NON_NULL) над всеми DTO
3. А почему при запросе пользователя кидаем RuntimException? так определяем, что нет команд?
4. При апдейте пользователя(команда) мы передаем имя команды (т.е. так можно кучу команд насоздовать?)
5. Нет валидации, что уже есть капитан на стороне сервера
6. сделать логаут через сервера
7. Убери "Забыли пароль", этого у нас пока не будет.
8. После регистрации, если мы уже получили токен, то может сразу на комнату?
9. у всех entity над ID замени на @GeneratedValue(strategy=GenerationType.IDENTITY), так сама БАЗА будет генерить АЙДИ, а JPA просто его брать(раньше сама генерила и видимо в этом была причина двойного инкремента)
10. в application.yaml добавь
url: jdbc:postgresql://localhost:5432/${spring.datasource.name}
spring.datasource.driver-class-name: org.postgresql.Driver
spring.jpa.generate-ddl: false 

по последнему - JPA пытается сгенерить SQL на основе описания твоих entity, и более того, применить его. Нам этого не надо.

**Comment by igor-sumin** [comment]
1. добавил возможность получения всей информации о пользователе в UserController - getUserInfo
2. добавил аннотацию в некоторые DTO
3. исправил исключение на CodeNamesExceptions с описанием выброшенной ошибки, иначе без обработки orElseThrow мы получим Optional<Team> вместо желаемого Team
4. в принципе, возможно насоздавать кучу команд, однако на клиенте выбор падает только на команды Red и Blue
5. добавил проверку в UserService - updateUser
7. убрал
8. сделал
9. заменил
10. добавил
